import { FileJson, Box, Shield, MapPin, Activity, FileCode } from "lucide-react";

const outputs = [
  {
    icon: <Box className="w-6 h-6" />,
    title: "Render Meshes",
    items: ["LOD0/LOD1/LOD2 generated by resampling (Nu, Nv)", "No decimation—topology controlled by design", "GLB export per LOD"],
  },
  {
    icon: <Shield className="w-6 h-6" />,
    title: "Collision",
    items: ["Primitive colliders (capsules/boxes)", "Simplified collision mesh from low LOD", "Hybrid mode recommended"],
  },
  {
    icon: <Activity className="w-6 h-6" />,
    title: "Proxies",
    items: ["Union-of-spheres for hull/water coupling", "Buoyancy sample points (≤64)", "Aero surface patches"],
  },
  {
    icon: <MapPin className="w-6 h-6" />,
    title: "Hardpoints",
    items: ["Resolved world transforms", "Rigging/spars/rudder attachments", "Defined in design space (u, s)"],
  },
  {
    icon: <FileJson className="w-6 h-6" />,
    title: "Diagnostics",
    items: ["Ortho renders (top/side/front/rear)", "Error arrays + fit report", "Patch history timeline"],
  },
  {
    icon: <FileCode className="w-6 h-6" />,
    title: "Manifest",
    items: ["Build hash for reproducibility", "Version + compiler metadata", "Complete asset bundle index"],
  },
];

const OutputsSection = () => {
  return (
    <section className="py-24">
      <div className="container px-4">
        <div className="text-center mb-16">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">
            Runtime <span className="text-accent">Outputs</span>
          </h2>
          <p className="text-muted-foreground max-w-2xl mx-auto">
            Every compile produces a complete, game-ready AssetBundle
          </p>
        </div>

        {/* Bundle structure preview */}
        <div className="max-w-3xl mx-auto mb-16">
          <div className="rounded-lg border border-border bg-card overflow-hidden">
            <div className="px-4 py-3 border-b border-border bg-muted/30">
              <span className="font-mono text-sm text-muted-foreground">AssetBundle/</span>
            </div>
            <div className="p-4 font-mono text-sm space-y-1">
              <div className="text-foreground">├── manifest.json</div>
              <div className="text-primary">├── meshes/</div>
              <div className="text-muted-foreground pl-4">│   ├── LOD0.glb</div>
              <div className="text-muted-foreground pl-4">│   ├── LOD1.glb</div>
              <div className="text-muted-foreground pl-4">│   └── LOD2.glb</div>
              <div className="text-accent">├── collision/</div>
              <div className="text-muted-foreground pl-4">│   ├── colliders.json</div>
              <div className="text-muted-foreground pl-4">│   └── collisionMesh.glb</div>
              <div className="text-primary">├── proxies/</div>
              <div className="text-muted-foreground pl-4">│   ├── buoyancySpheres.json</div>
              <div className="text-muted-foreground pl-4">│   └── aeroProxies.json</div>
              <div className="text-accent">├── hardpoints/</div>
              <div className="text-muted-foreground pl-4">│   └── hardpoints.json</div>
              <div className="text-primary">├── diagnostics/</div>
              <div className="text-muted-foreground pl-4">│   ├── ortho_*.png</div>
              <div className="text-muted-foreground pl-4">│   ├── error_curves.json</div>
              <div className="text-muted-foreground pl-4">│   └── fit_report.json</div>
              <div className="text-accent">└── history/</div>
              <div className="text-muted-foreground pl-4">    ├── patches.jsonl</div>
              <div className="text-muted-foreground pl-4">    └── spec_snapshot.json</div>
            </div>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 max-w-6xl mx-auto">
          {outputs.map((output) => (
            <div
              key={output.title}
              className="p-6 rounded-lg border border-border bg-card hover:border-primary/30 transition-colors"
            >
              <div className="w-12 h-12 rounded-lg bg-primary/10 flex items-center justify-center text-primary mb-4">
                {output.icon}
              </div>
              <h3 className="text-lg font-semibold mb-3">{output.title}</h3>
              <ul className="space-y-2">
                {output.items.map((item, idx) => (
                  <li key={idx} className="flex items-start gap-2 text-sm text-muted-foreground">
                    <span className="text-accent mt-1.5">•</span>
                    {item}
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default OutputsSection;
