// Shallow Water Equations fragment shaders for GPGPU ping-pong computation
// State texture layout: R=height, G=velocityX, B=velocityZ, A=foam

export const swePassthroughVertex = /* glsl */ `
varying vec2 vUv;
void main() {
  vUv = uv;
  gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
}
`;

// Main SWE advection + pressure gradient update
export const sweAdvectionShader = /* glsl */ `
uniform sampler2D uPrevState;
uniform float uDt;
uniform float uDx;
uniform vec2 uResolution;
uniform float uGravity;
uniform float uDamping;

varying vec2 vUv;

void main() {
  vec2 texel = 1.0 / uResolution;

  // Current state
  vec4 state = texture2D(uPrevState, vUv);
  float h  = state.r;
  float vx = state.g;
  float vz = state.b;
  float foam = state.a;

  // Semi-Lagrangian back-trace
  vec2 backUV = vUv - vec2(vx, vz) * uDt / (uDx * uResolution);
  backUV = clamp(backUV, texel, 1.0 - texel);
  vec4 advected = texture2D(uPrevState, backUV);

  // Neighbor heights for pressure gradient
  float hL = texture2D(uPrevState, vUv - vec2(texel.x, 0.0)).r;
  float hR = texture2D(uPrevState, vUv + vec2(texel.x, 0.0)).r;
  float hB = texture2D(uPrevState, vUv - vec2(0.0, texel.y)).r;
  float hT = texture2D(uPrevState, vUv + vec2(0.0, texel.y)).r;

  // Pressure gradient (gravity * height gradient)
  float dhdx = (hR - hL) / (2.0 * uDx);
  float dhdz = (hT - hB) / (2.0 * uDx);

  // Velocity update
  float newVx = advected.g - uGravity * dhdx * uDt;
  float newVz = advected.b - uGravity * dhdz * uDt;

  // Damping
  float d = 1.0 - uDamping * uDt;
  newVx *= d;
  newVz *= d;

  // Height from velocity divergence
  float vxL = texture2D(uPrevState, vUv - vec2(texel.x, 0.0)).g;
  float vxR = texture2D(uPrevState, vUv + vec2(texel.x, 0.0)).g;
  float vzB = texture2D(uPrevState, vUv - vec2(0.0, texel.y)).b;
  float vzT = texture2D(uPrevState, vUv + vec2(0.0, texel.y)).b;

  float divergence = ((vxR - vxL) + (vzT - vzB)) / (2.0 * uDx);
  float newH = advected.r - divergence * uDt;

  // Stability clamps
  newH  = clamp(newH, -3.0, 3.0);
  newVx = clamp(newVx, -15.0, 15.0);
  newVz = clamp(newVz, -15.0, 15.0);

  // Foam: generated by velocity magnitude, decays over time
  float speed = length(vec2(newVx, newVz));
  float foamGen = smoothstep(1.0, 4.0, speed) * 0.3;
  float newFoam = advected.a * 0.97 + foamGen * uDt; // decay + generation
  newFoam = clamp(newFoam, 0.0, 1.0);

  gl_FragColor = vec4(newH, newVx, newVz, newFoam);
}
`;

// Object coupling: applies boat hull displacement and wake forces
export const sweObjectCouplingShader = /* glsl */ `
uniform sampler2D uPrevState;
uniform sampler2D uObjectMask;  // R=depth, G=velX, B=velZ, A=radius
uniform float uDt;
uniform float uCouplingStrength;
uniform vec2 uResolution;

varying vec2 vUv;

void main() {
  vec4 state = texture2D(uPrevState, vUv);
  vec4 obj   = texture2D(uObjectMask, vUv);

  float objDepth = obj.r;
  vec2  objVel   = obj.gb;

  if (objDepth > 0.001) {
    // Volume displacement: push water down where hull is
    state.r -= objDepth * uCouplingStrength * uDt;

    // Momentum transfer: boat velocity → water
    state.g += objVel.x * uCouplingStrength * uDt * 0.3;
    state.b += objVel.y * uCouplingStrength * uDt * 0.3;

    // Wake generation: radial push proportional to speed
    float speed = length(objVel);
    float wake = objDepth * speed * 0.15;
    state.r += wake * uDt;

    // Wake foam
    state.a += speed * objDepth * 0.1 * uDt;
    state.a = clamp(state.a, 0.0, 1.0);
  }

  gl_FragColor = state;
}
`;

// Breach feedback: applies particle impact ring waves back to heightfield
export const sweBreachFeedbackShader = /* glsl */ `
uniform sampler2D uPrevState;
uniform sampler2D uBFT;  // Breach feedback: R=heightImpulse, G=momX, B=momZ
uniform float uDt;
uniform vec2 uResolution;

varying vec2 vUv;

void main() {
  vec4 state = texture2D(uPrevState, vUv);
  vec4 feedback = texture2D(uBFT, vUv);

  // Apply particle impact impulses
  state.r += feedback.r * uDt;
  state.g += feedback.g * uDt;
  state.b += feedback.b * uDt;

  // Feedback-generated foam
  float impactStrength = length(feedback.rgb);
  state.a += impactStrength * 0.2 * uDt;
  state.a = clamp(state.a, 0.0, 1.0);

  gl_FragColor = state;
}
`;
